/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "shopC.h"


void
shop_client_1(char *host,char fr,int quant)
{
	CLIENT *clnt;
	char * *result_1;
	inputVec  buyfruit_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SHOP_CLIENT, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	buyfruit_1_arg.Fname=fr;
	buyfruit_1_arg.quantity=quant;
	result_1 = buyfruit_1(&buyfruit_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("%s",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host FRUIT_INITIAL FRUIT_QUANTITY\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	shop_client_1 (host,*argv[2],atoi(argv[3]));
exit (0);
}
