/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "shopC.h"
#include <pthread.h>
#include <semaphore.h>



void w2file(int* fruits){ 
    FILE *filePointer ;
    filePointer = fopen("DB.txt", "w") ;
    for (int i=0;i<4;i++){ 
        fprintf(filePointer,"%d",*(fruits+i)) ;    
        fprintf(filePointer," ") ;
    }
  fclose(filePointer) ;  
}

void read4file(int* fruits) 
{  
 FILE* file = fopen ("DB.txt", "r");
  int i = 0;
  fscanf (file, "%d", &i);    
  for (int p=0;p<4;p++)
    { 
      *(fruits+p)=i;
      fscanf (file, "%d", &i);      
    }
  fclose (file);        
}


char* ProMango(int quant,int fruits[]){
	if(quant > fruits[0]){
		char *buffer=(char*)malloc(1024);;
		bzero(buffer, 1024);
		sprintf(buffer, "\nServer:Sorry Not enough Mangoes are present in the shop.\nThe available fruits are:\nMango: %d\nApple: %d\nKiwiw: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
		printf("\nCustomer ordered More Mangoes than are available.\n");
		return buffer;
	}
	printf("Customer Ordered %d Mangoes\n",quant);
	fruits[0]-=quant;
	w2file(fruits);
	char *buffer=(char*)malloc(1024);;
	bzero(buffer, 1024);
	sprintf(buffer, "\nServer:Thanks for ordering.\nThe available fruits are:\nMango: %d\nApple: %d\nKiwi: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
	printf("The available fruits are:\nMango: %d\nApple: %d\nKiwiw: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
	return buffer;
}

char* ProApple(int quant,int fruits[]){
	if(quant > fruits[1]){
		char *buffer=(char*)malloc(1024);;
		bzero(buffer, 1024);
		sprintf(buffer, "\nServer:Sorry Not enough Apples are present in the shop.\nThe available fruits are:\nMango: %d\nApple: %d\nKiwiw: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
		printf("\nCustomer ordered More Apples than are available.\n");
		return buffer;
	}
	printf("Customer Ordered %d Apples\n",quant);
	fruits[1]-=quant;
	w2file(fruits);
	char *buffer=(char*)malloc(1024);;
	bzero(buffer, 1024);
	sprintf(buffer, "\nServer:Thanks for ordering.\nThe available fruits are:\nMango: %d\nApple: %d\nKiwi: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
	printf("The available fruits are:\nMango: %d\nApple: %d\nKiwiw: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
	return buffer;	
}

char* ProKiwi(int quant,int fruits[]){
	if(quant > fruits[2]){
		char *buffer=(char*)malloc(1024);;
		bzero(buffer, 1024);
		sprintf(buffer, "\nServer:Sorry Not enough Kiwi are present in the shop.\nThe available fruits are:\nMango: %d\nApple: %d\nKiwiw: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
		printf("\nCustomer ordered More Kiwis than are available.\n");
		return buffer;
	}
	printf("Customer Ordered %d Kiwi\n",quant);
	fruits[2]-=quant;
	w2file(fruits);
	char *buffer=(char*)malloc(1024);;
	bzero(buffer, 1024);
	sprintf(buffer, "\nServer:Thanks for ordering.\nThe available fruits are:\nMango: %d\nApple: %d\nKiwi: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
	printf("The available fruits are:\nMango: %d\nApple: %d\nKiwiw: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
	return buffer;	
}

char* ProBanana(int quant,int fruits[]){
	if(quant > fruits[3]){
		char *buffer=(char*)malloc(1024);;
		bzero(buffer, 1024);
		sprintf(buffer, "\nServer:Sorry Not enough Banana are present in the shop.\nThe available fruits are:\nMango: %d\nApple: %d\nKiwiw: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
		printf("\nCustomer ordered More Bananas than are available.\n");
		return buffer;
	}
	printf("Customer Ordered %d Banana\n",quant);
	fruits[3]-=quant;
	w2file(fruits);
	char *buffer=(char*)malloc(1024);;
	bzero(buffer, 1024);
	sprintf(buffer, "\nServer:Thanks for ordering.\nThe available fruits are:\nMango: %d\nApple: %d\nKiwi: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
	printf("\nThe available fruits are:\nMango: %d\nApple: %d\nKiwiw: %d\nBanana: %d\n",fruits[0],fruits[1],fruits[2],fruits[3]);
	return buffer;	
}
char **
buyfruit_1_svc(inputVec *argp, struct svc_req *rqstp)
{
	printf("Welcome to Fruit Shop\n");
	static char * result;
	int fruits[4];
	char buffer[1024];
	read4file(fruits);
	switch (argp->Fname){
		case 'M':result=ProMango(argp->quantity,fruits);
				 break;
		case 'm':result=ProMango(argp->quantity,fruits);
				 break;
		case 'A':result=ProApple(argp->quantity,fruits);
				 break;
		case 'a':result=ProApple(argp->quantity,fruits);
				 break;
		case 'K':result=ProKiwi(argp->quantity,fruits);
				 break;
		case 'k':result=ProKiwi(argp->quantity,fruits);
				 break;
		case 'B':result=ProBanana(argp->quantity,fruits);
				 break;
		case 'b':result=ProBanana(argp->quantity,fruits);
				 break; 
		default: bzero(buffer, sizeof(buffer));
				 sprintf(buffer, "\nWrong parameters passed please enter correct Parameters: \n");
				 result = buffer;
				 break;
	}

	return &result;
}
